/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as StaffReceptionRouteImport } from './routes/staff.reception'
import { Route as StaffMarketingRouteImport } from './routes/staff.marketing'
import { Route as StaffFinanceRouteImport } from './routes/staff.finance'
import { Route as StaffBranchRouteImport } from './routes/staff.branch'
import { Route as DashboardVisitorsRouteImport } from './routes/dashboard.visitors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardMembershipRouteImport } from './routes/dashboard.membership'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as AdminWorkflowsRouteImport } from './routes/admin.workflows'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicCorporateRouteImport } from './routes/_public/corporate'
import { Route as PublicBookVisitRouteImport } from './routes/_public/book-visit'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as StaffSalesIndexRouteImport } from './routes/staff.sales.index'
import { Route as PublicBranchesIndexRouteImport } from './routes/_public/branches.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog.index'
import { Route as StaffSalesLeadIdRouteImport } from './routes/staff.sales.$leadId'
import { Route as PublicBranchesSlugRouteImport } from './routes/_public/branches.$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog.$slug'
import { Route as PublicAuthResetRouteImport } from './routes/_public/auth.reset'
import { Route as PublicAuthForgotRouteImport } from './routes/_public/auth.forgot'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const StaffReceptionRoute = StaffReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMarketingRoute = StaffMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceRoute = StaffFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBranchRoute = StaffBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardVisitorsRoute = DashboardVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCorporateRoute = PublicCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookVisitRoute = PublicBookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const StaffSalesIndexRoute = StaffSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => StaffRoute,
} as any)
const PublicBranchesIndexRoute = PublicBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const StaffSalesLeadIdRoute = StaffSalesLeadIdRouteImport.update({
  id: '/sales/$leadId',
  path: '/sales/$leadId',
  getParentRoute: () => StaffRoute,
} as any)
const PublicBranchesSlugRoute = PublicBranchesSlugRouteImport.update({
  id: '/branches/$slug',
  path: '/branches/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetRoute = PublicAuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthForgotRoute = PublicAuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => PublicAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/book-visit': typeof PublicBookVisitRoute
  '/corporate': typeof PublicCorporateRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/forgot': typeof PublicAuthForgotRoute
  '/auth/reset': typeof PublicAuthResetRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/branches/$slug': typeof PublicBranchesSlugRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/branches/': typeof PublicBranchesIndexRoute
  '/staff/sales/': typeof StaffSalesIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/book-visit': typeof PublicBookVisitRoute
  '/corporate': typeof PublicCorporateRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/forgot': typeof PublicAuthForgotRoute
  '/auth/reset': typeof PublicAuthResetRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/branches/$slug': typeof PublicBranchesSlugRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/blog': typeof PublicBlogIndexRoute
  '/branches': typeof PublicBranchesIndexRoute
  '/staff/sales': typeof StaffSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_public/book-visit': typeof PublicBookVisitRoute
  '/_public/corporate': typeof PublicCorporateRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/auth/forgot': typeof PublicAuthForgotRoute
  '/_public/auth/reset': typeof PublicAuthResetRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/branches/$slug': typeof PublicBranchesSlugRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/branches/': typeof PublicBranchesIndexRoute
  '/staff/sales/': typeof StaffSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/staff'
    | '/auth'
    | '/book-visit'
    | '/corporate'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/coupons'
    | '/admin/data'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/site'
    | '/admin/users'
    | '/admin/workflows'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/dashboard/'
    | '/auth/forgot'
    | '/auth/reset'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/staff/sales/$leadId'
    | '/blog/'
    | '/branches/'
    | '/staff/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/staff'
    | '/auth'
    | '/book-visit'
    | '/corporate'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/coupons'
    | '/admin/data'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/site'
    | '/admin/users'
    | '/admin/workflows'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/staff/sales/$leadId'
    | '/blog'
    | '/branches'
    | '/staff/sales'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/dashboard'
    | '/staff'
    | '/_public/auth'
    | '/_public/book-visit'
    | '/_public/corporate'
    | '/_public/pricing'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/coupons'
    | '/admin/data'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/site'
    | '/admin/users'
    | '/admin/workflows'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/_public/'
    | '/dashboard/'
    | '/_public/auth/forgot'
    | '/_public/auth/reset'
    | '/_public/blog/$slug'
    | '/_public/branches/$slug'
    | '/staff/sales/$leadId'
    | '/_public/blog/'
    | '/_public/branches/'
    | '/staff/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/staff/reception': {
      id: '/staff/reception'
      path: '/reception'
      fullPath: '/staff/reception'
      preLoaderRoute: typeof StaffReceptionRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/marketing': {
      id: '/staff/marketing'
      path: '/marketing'
      fullPath: '/staff/marketing'
      preLoaderRoute: typeof StaffMarketingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance': {
      id: '/staff/finance'
      path: '/finance'
      fullPath: '/staff/finance'
      preLoaderRoute: typeof StaffFinanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/branch': {
      id: '/staff/branch'
      path: '/branch'
      fullPath: '/staff/branch'
      preLoaderRoute: typeof StaffBranchRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/visitors': {
      id: '/dashboard/visitors'
      path: '/visitors'
      fullPath: '/dashboard/visitors'
      preLoaderRoute: typeof DashboardVisitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/membership': {
      id: '/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof DashboardMembershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/corporate': {
      id: '/_public/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof PublicCorporateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/book-visit': {
      id: '/_public/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof PublicBookVisitRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/staff/sales/': {
      id: '/staff/sales/'
      path: '/sales'
      fullPath: '/staff/sales/'
      preLoaderRoute: typeof StaffSalesIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_public/branches/': {
      id: '/_public/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof PublicBranchesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/staff/sales/$leadId': {
      id: '/staff/sales/$leadId'
      path: '/sales/$leadId'
      fullPath: '/staff/sales/$leadId'
      preLoaderRoute: typeof StaffSalesLeadIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_public/branches/$slug': {
      id: '/_public/branches/$slug'
      path: '/branches/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof PublicBranchesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset': {
      id: '/_public/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof PublicAuthResetRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/forgot': {
      id: '/_public/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof PublicAuthForgotRouteImport
      parentRoute: typeof PublicAuthRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthForgotRoute: typeof PublicAuthForgotRoute
  PublicAuthResetRoute: typeof PublicAuthResetRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthForgotRoute: PublicAuthForgotRoute,
  PublicAuthResetRoute: PublicAuthResetRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicBookVisitRoute: typeof PublicBookVisitRoute
  PublicCorporateRoute: typeof PublicCorporateRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBranchesSlugRoute: typeof PublicBranchesSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicBranchesIndexRoute: typeof PublicBranchesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicBookVisitRoute: PublicBookVisitRoute,
  PublicCorporateRoute: PublicCorporateRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBranchesSlugRoute: PublicBranchesSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicBranchesIndexRoute: PublicBranchesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardMembershipRoute: typeof DashboardMembershipRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVisitorsRoute: typeof DashboardVisitorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVisitorsRoute: DashboardVisitorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffRouteChildren {
  StaffBranchRoute: typeof StaffBranchRoute
  StaffFinanceRoute: typeof StaffFinanceRoute
  StaffMarketingRoute: typeof StaffMarketingRoute
  StaffReceptionRoute: typeof StaffReceptionRoute
  StaffSalesLeadIdRoute: typeof StaffSalesLeadIdRoute
  StaffSalesIndexRoute: typeof StaffSalesIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBranchRoute: StaffBranchRoute,
  StaffFinanceRoute: StaffFinanceRoute,
  StaffMarketingRoute: StaffMarketingRoute,
  StaffReceptionRoute: StaffReceptionRoute,
  StaffSalesLeadIdRoute: StaffSalesLeadIdRoute,
  StaffSalesIndexRoute: StaffSalesIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
