/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as StaffReceptionRouteImport } from './routes/staff.reception'
import { Route as StaffMarketingRouteImport } from './routes/staff.marketing'
import { Route as StaffFinanceRouteImport } from './routes/staff.finance'
import { Route as StaffBranchRouteImport } from './routes/staff.branch'
import { Route as DashboardVisitorsRouteImport } from './routes/dashboard.visitors'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardMembershipRouteImport } from './routes/dashboard.membership'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BranchesSlugRouteImport } from './routes/branches.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWorkflowsRouteImport } from './routes/admin.workflows'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as StaffSalesIndexRouteImport } from './routes/staff.sales.index'
import { Route as StaffSalesLeadIdRouteImport } from './routes/staff.sales.$leadId'
import { Route as ApiMockPlansRouteImport } from './routes/api/mock/plans'
import { Route as ApiMockLeadsRouteImport } from './routes/api/mock/leads'
import { Route as ApiMockBranchesRouteImport } from './routes/api/mock/branches'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReceptionRoute = StaffReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMarketingRoute = StaffMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceRoute = StaffFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBranchRoute = StaffBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardVisitorsRoute = DashboardVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembershipRoute = DashboardMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const BranchesSlugRoute = BranchesSlugRouteImport.update({
  id: '/branches/$slug',
  path: '/branches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const StaffSalesIndexRoute = StaffSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSalesLeadIdRoute = StaffSalesLeadIdRouteImport.update({
  id: '/sales/$leadId',
  path: '/sales/$leadId',
  getParentRoute: () => StaffRoute,
} as any)
const ApiMockPlansRoute = ApiMockPlansRouteImport.update({
  id: '/api/mock/plans',
  path: '/api/mock/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockLeadsRoute = ApiMockLeadsRouteImport.update({
  id: '/api/mock/leads',
  path: '/api/mock/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockBranchesRoute = ApiMockBranchesRouteImport.update({
  id: '/api/mock/branches',
  path: '/api/mock/branches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/blog/': typeof BlogIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mock/branches': typeof ApiMockBranchesRoute
  '/api/mock/leads': typeof ApiMockLeadsRoute
  '/api/mock/plans': typeof ApiMockPlansRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/staff/sales/': typeof StaffSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/corporate': typeof CorporateRoute
  '/pricing': typeof PricingRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/blog': typeof BlogIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/mock/branches': typeof ApiMockBranchesRoute
  '/api/mock/leads': typeof ApiMockLeadsRoute
  '/api/mock/plans': typeof ApiMockPlansRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/staff/sales': typeof StaffSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/corporate': typeof CorporateRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/membership': typeof DashboardMembershipRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/visitors': typeof DashboardVisitorsRoute
  '/staff/branch': typeof StaffBranchRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/reception': typeof StaffReceptionRoute
  '/blog/': typeof BlogIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mock/branches': typeof ApiMockBranchesRoute
  '/api/mock/leads': typeof ApiMockLeadsRoute
  '/api/mock/plans': typeof ApiMockPlansRoute
  '/staff/sales/$leadId': typeof StaffSalesLeadIdRoute
  '/staff/sales/': typeof StaffSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-visit'
    | '/corporate'
    | '/dashboard'
    | '/pricing'
    | '/staff'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/workflows'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/blog/'
    | '/branches/'
    | '/dashboard/'
    | '/api/mock/branches'
    | '/api/mock/leads'
    | '/api/mock/plans'
    | '/staff/sales/$leadId'
    | '/staff/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-visit'
    | '/corporate'
    | '/pricing'
    | '/staff'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/workflows'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/blog'
    | '/branches'
    | '/dashboard'
    | '/api/mock/branches'
    | '/api/mock/leads'
    | '/api/mock/plans'
    | '/staff/sales/$leadId'
    | '/staff/sales'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book-visit'
    | '/corporate'
    | '/dashboard'
    | '/pricing'
    | '/staff'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/forms'
    | '/admin/pricing'
    | '/admin/users'
    | '/admin/workflows'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/dashboard/bookings'
    | '/dashboard/community'
    | '/dashboard/invoices'
    | '/dashboard/membership'
    | '/dashboard/referrals'
    | '/dashboard/visitors'
    | '/staff/branch'
    | '/staff/finance'
    | '/staff/marketing'
    | '/staff/reception'
    | '/blog/'
    | '/branches/'
    | '/dashboard/'
    | '/api/mock/branches'
    | '/api/mock/leads'
    | '/api/mock/plans'
    | '/staff/sales/$leadId'
    | '/staff/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookVisitRoute: typeof BookVisitRoute
  CorporateRoute: typeof CorporateRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  StaffRoute: typeof StaffRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BranchesSlugRoute: typeof BranchesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  ApiMockBranchesRoute: typeof ApiMockBranchesRoute
  ApiMockLeadsRoute: typeof ApiMockLeadsRoute
  ApiMockPlansRoute: typeof ApiMockPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reception': {
      id: '/staff/reception'
      path: '/reception'
      fullPath: '/staff/reception'
      preLoaderRoute: typeof StaffReceptionRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/marketing': {
      id: '/staff/marketing'
      path: '/marketing'
      fullPath: '/staff/marketing'
      preLoaderRoute: typeof StaffMarketingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance': {
      id: '/staff/finance'
      path: '/finance'
      fullPath: '/staff/finance'
      preLoaderRoute: typeof StaffFinanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/branch': {
      id: '/staff/branch'
      path: '/branch'
      fullPath: '/staff/branch'
      preLoaderRoute: typeof StaffBranchRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/visitors': {
      id: '/dashboard/visitors'
      path: '/visitors'
      fullPath: '/dashboard/visitors'
      preLoaderRoute: typeof DashboardVisitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/membership': {
      id: '/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof DashboardMembershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/branches/$slug': {
      id: '/branches/$slug'
      path: '/branches/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof BranchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/sales/': {
      id: '/staff/sales/'
      path: '/sales'
      fullPath: '/staff/sales/'
      preLoaderRoute: typeof StaffSalesIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/sales/$leadId': {
      id: '/staff/sales/$leadId'
      path: '/sales/$leadId'
      fullPath: '/staff/sales/$leadId'
      preLoaderRoute: typeof StaffSalesLeadIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/mock/plans': {
      id: '/api/mock/plans'
      path: '/api/mock/plans'
      fullPath: '/api/mock/plans'
      preLoaderRoute: typeof ApiMockPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/leads': {
      id: '/api/mock/leads'
      path: '/api/mock/leads'
      fullPath: '/api/mock/leads'
      preLoaderRoute: typeof ApiMockLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/branches': {
      id: '/api/mock/branches'
      path: '/api/mock/branches'
      fullPath: '/api/mock/branches'
      preLoaderRoute: typeof ApiMockBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardMembershipRoute: typeof DashboardMembershipRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardVisitorsRoute: typeof DashboardVisitorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardMembershipRoute: DashboardMembershipRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardVisitorsRoute: DashboardVisitorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffRouteChildren {
  StaffBranchRoute: typeof StaffBranchRoute
  StaffFinanceRoute: typeof StaffFinanceRoute
  StaffMarketingRoute: typeof StaffMarketingRoute
  StaffReceptionRoute: typeof StaffReceptionRoute
  StaffSalesLeadIdRoute: typeof StaffSalesLeadIdRoute
  StaffSalesIndexRoute: typeof StaffSalesIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBranchRoute: StaffBranchRoute,
  StaffFinanceRoute: StaffFinanceRoute,
  StaffMarketingRoute: StaffMarketingRoute,
  StaffReceptionRoute: StaffReceptionRoute,
  StaffSalesLeadIdRoute: StaffSalesLeadIdRoute,
  StaffSalesIndexRoute: StaffSalesIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookVisitRoute: BookVisitRoute,
  CorporateRoute: CorporateRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  StaffRoute: StaffRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BranchesSlugRoute: BranchesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  ApiMockBranchesRoute: ApiMockBranchesRoute,
  ApiMockLeadsRoute: ApiMockLeadsRoute,
  ApiMockPlansRoute: ApiMockPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
